### ISSUE TITLE
Allow for specifying separate build-time and runtime system-level dependencies

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#105]
It would be cool to have a way of avoiding crud like gcc and python3-devel in the final images.

This may be a perfect use case for bindep "profiles". There could be a `build` profile that we install at the beginning of the build and uninstall at the end.

**Comment by pabelanger** [comment]
++ I dont mind looking into this

**Comment by shanemcd** [comment]
I ended up hacking on this in #148

**Comment by AlanCoding** [comment]
Closing as implemented, we have another issue discussing documentation for this.
