### ISSUE TITLE
Local execution use case?

### ISSUE THREAD

**Issue by snooyen** [ansible/ansible-builder#125]
Is this project purely directed at setting up execution environments for AWX / Tower use cases?

Specifically, would the community be able to use this project to distribute containerized execution environments that engineers can use on their local workstations to execute Ansible code?

To that end, is there a way to specify Ansible / Python versions for a given execution environment?

What about inclusion of other binary dependencies that can't be handled through bindep? (namely terraform, kubectl, eksctl, etc...)

**Comment by AlanCoding** [comment]
ansible-builder is basically a tool for one part of an image build. It needs a base image conforming to certain things (like having Ansible installed), and in practice we are only supporting the official base image, which comes from:

https://github.com/ansible/ansible-runner/blob/devel/Dockerfile

In the execution environment definition you can add extra build steps to install things like terraform.

Or, you could do any level of customization either to the ansible-runner image before where builder comes in, or in layers after what builder does.
