### ISSUE TITLE
Print absolute path to build context directory in output.

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible-builder#128]
```
Complete! The build context can be found at: context
```

What does this mean?

**Comment by AlanCoding** [comment]
When you run `ansible-builder build`, it takes your Execution Environment Definition as input. From that, it produces two outputs, the image and the build context.

The build context can be reused later to make the same image again, even if you don't have `ansible-builder` installed.

**Comment by shanemcd** [comment]
This has been on my mind for a while. I'd like the output to print out an absolute path. Going to rename this issue.

**Comment by AlanCoding** [comment]
printing absolute path now and calling it done
