### ISSUE TITLE
Need flag to force Dockerfile or Container file, regardless of container runtime

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#152]
We have a requirement downstream, to use podman for builds.  However, by using the podman container-runetime, we hardcore Containerfile.

In some cases, people run podman, but still expect Dockerfile to be used.  The way to work around this is to create a symlink
```
ln -s Containerfile Dockerfile
```

But we should expose a way for the user to pick the filename, independent of container-runtime.

**Comment by AlanCoding** [comment]
Added `--output-filename=Dockerfile/Containerfile`
