### ISSUE TITLE
Removed duplicate requirements.yml file

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#153]
Because we need a requirements.yml file, to tell ansible-builder with collections to install, we 'copy' that requirements.yml file into the context folder.  This leaves the user with 2 requirements.yml files, to store in git.

We should allow for the requirements.yml file to exist under the context folder, and if it does re-used it, rather then copying it back into the top-level context folder.

https://github.com/ansible/network-ee/ is an example where requirements.yml is stored under tools/ but also copied into top-level directory.

**Comment by AlanCoding** [comment]
The awx-ee solves the problem by placing it under `_build/requirements.yml`.

https://github.com/ansible/awx-ee/blob/a4dbae5690927497ff2c0b7a681788e416115fd4/_build/requirements.yml

Does this then boil down to a docs issue?

**Comment by shanemcd** [comment]
This is fixed https://github.com/ansible/ansible-builder/pull/217
