### ISSUE TITLE
Document compile/epel bindep profiles

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#156]
These new profiles were introduced when https://github.com/ansible/ansible-runner/pull/581 landed. We should explain how they work somewhere in the ansible-builder documentation.

**Comment by AlanCoding** [comment]
Copying from prior issue

----

We have a proposal that we would document certain bindep profiles that, if included by a collection, would trigger certain behavior by `ansible-builder`. We have discussed:

 - `epel` - if a collection had entries with this profile, then the epel repo would be enabled before installing those requirements
 - `compile` - if a collection had entries with this profile, then it would indicate that it is needed to install _other_ requirements (python ones specifically), but not required to be in the final build. Several are being dealt with at the https://github.com/ansible/awx-ee repo

This ~would be~ was a notable addition to the core feature set of ansible-builder, and needs to be documented.

**Comment by howardjones** [comment]
I'm 8 hours into a "pip install" run - does it ever actually give up?
(trying to build an ansible execution container with azure-cli and azure.azcollection inside)

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible-builder/pull/595
