### ISSUE TITLE
Report filtered dependencies in output from introspect

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#187]
We skip certain requirements (mostly python ones) for various reasons:

https://github.com/ansible/ansible-builder/blob/f53d6415128c918d00c046c6eba040be95cd2fa2/ansible_builder/requirements.py#L7

We should have a separate section in the YAML outputted from the introspect script that lists the lines which were scrubbed from these files - for transparency.

**Comment by Akasurde** [comment]
resolved_by_pr #232
