### ISSUE TITLE
Allow specifying secrets to download collections from custom locations

### ISSUE THREAD

**Issue by ghost** [ansible/ansible-builder#196]
A general use case here would be to download collections from a private git repository, there should be a way to specify a token/key to be mounted onto the container for this purpose

**Comment by JustInVTime** [comment]
:+1:

**Comment by AlanCoding** [comment]
Going to close as duplicate of https://github.com/ansible/ansible-builder/issues/195

If there's any specific means of passing secrets, please contribute to the discussion there. Thanks.
