### ISSUE TITLE
final tag shouldn't be applied to intermediate image

### ISSUE THREAD

**Issue by ChetRHosey** [ansible/ansible-builder#197]
`ansible-builder build` clobbers the existing tag even if it encounters an error.

As I understand it, the following process is used:

1) Build a temporary image with the required collections and modules. Apply the default or user-specified tag to this image.
2) Reference the tag to run introspect.py within that image to identify dependencies.
3) Build the final image with all dependencies. Apply the default or user-specified tag to this image.

If the target tag initially points to a functional image, but steps 2 or 3 fail during an ansible-builder run, then the tag will now point to an image that can't be used to run playbooks.

Ideally the target tag would only be updated after successful completion of step 3.

**Comment by AlanCoding** [comment]
This should get resolved by https://github.com/ansible/ansible-builder/pull/217
