### ISSUE TITLE
Feature to ignore/sanitize some bindep requirements

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible-builder#201]
Currently the `sanitize_requirements` only works with python requirements and doesn't work for the binary dependencies.
While working with some partner collections we have noticed below requirements in bindep.txt
```
# This is a cross-platform list tracking distribution packages needed by this collection;
# see https://docs.openstack.org/infra/bindep/ for additional information.

python >=3.6,<=3.8
```
This causes failure while building as below with ubi8 images

```
There are following alternatives for "python": python2, python36, python38
Error: Unable to find a match: python
STEP 12: FROM registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-ee-minimal:ansible-automation-platform-2.0-rhel-8-containers-candidate-50443-20210329152500
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1
```
python as a requirement should be ignored in the bindep file[python38 is already installed in the base images]  and for that we would probably need to create a feature to sanitise binary dependencies.

**Comment by AlanCoding** [comment]
In cases we are relying on things like `python38-devel`

https://github.com/ansible/awx-ee/blob/devel/_build/bindep_combined.txt#L10

We might leave those untouched, I'm not sure.

**Comment by anshulbehl** [comment]
for this one I think we only need to sanitise when we see `python` in bindep file

**Comment by AlanCoding** [comment]
Could you link to a case of this? This shouldn't be too hard to implement but I want to know a little better what we're targeting.
