### ISSUE TITLE
Support PIP_OPTs for python-builder-image

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#211]
We added support to python-builder-image, which allows a user to pass pip options via PIP_OPTs:

  https://github.com/ansible/python-builder-image/pull/34
  
In the case of downstream builds, we set --no-build-isolation for reproducible builds. Additionally, it would allow upstream users to pass:

  --no-binary :all:

Which disabled use of pre-compiled wheels, again getting upstream builds closer to downstream / offline supported.

**Comment by AlanCoding** [comment]
How would users pass this option to ansible-builder? Would it be in the execution environment definition?

**Comment by pabelanger** [comment]
I imagined it working the same way we did the galaxy opts setting

**Comment by AlanCoding** [comment]
so a build arg.

The assemble script also takes, in some sense, CONSTRAINTS, PACKAGES, and others. I don't fully understand those options.

In my imagination, this would follow an `ARG` and then `ENV` pattern in the Containerfile. That wouldn't get messy if we add more later.

**Comment by tanganellilore** [comment]
@AlanCoding @Shrews I created a PR that will add this param. In the PR I wrote why we need this tipe of arg

Thanks

**Comment by Shrews** [comment]
I'm going to go ahead and close this. We just merged support for a new EE format that has features that would allow you highly customize any of the builder build phases (e.g., the new [`additional_build_steps` ](https://ansible-builder.readthedocs.io/en/latest/definition/#additional-build-steps) section).
