### ISSUE TITLE
Add ability to just generate contents of build folder

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-builder#212]
It would be helpful to allow of just running the generate build folder command, rather then a full build.

We have a use case downstream, where we want to generate the latest _build folder contents, but build using a different container build system.  Today we run ansible-builder, but ctrl-C when the 2nd stage builds start.

**Comment by AlanCoding** [comment]
Early in this project's history we have 2 primary actions, `ansible-builder create` and `ansible-builder build`. The "create" command would just create the build context without running the podman build command.

https://github.com/ansible/ansible-builder/blob/1c7b5d317399e18596e04500d4b68b2add91b6ad/ansible_builder/cli.py#L49-L56

This was no longer possible after we started running the "introspect" script outside of the container - which we are removing now.

So does the re-introduction of the create command match what you're saying here @pabelanger? That would be a well-defined task.

**Comment by shanemcd** [comment]
This is now possible with #217

**Comment by AlanCoding** [comment]
I'm going to say that this is ready for devel as the old `ansible-builder create` command.

**Comment by Akasurde** [comment]
PR #236 and #250 merged. Closing this issue. Please feel free to re-open if the problem persists. Thanks.
