### ISSUE TITLE
Deal with duplicate python / bindep requirements???

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#227]
https://github.com/ansible/awx-ee/blob/4e1c896e659acf549f12202c52b3035f8ee2dc24/_build/bindep_combined.txt#L2

https://github.com/ansible/awx-ee/blob/4e1c896e659acf549f12202c52b3035f8ee2dc24/_build/requirements_combined.txt#L8

Is it reasonable to have `requests` as a python requirement while also having `python38-requests` as a dnf requirement?

**Comment by Shrews** [comment]
The only `requests` reference in `ansible-builder` is in `docs/requirements.txt` and actually doesn't seem necessary to build the docs. I don't see the relationship to `awx-ee`. Can you elaborate?

**Comment by AlanCoding** [comment]
Requests will still creep into requirements, but won't appear in any of the files in the `_build` folder anymore. Collections will wind up listing it in cases like these:

https://github.com/ansible-collections/google.cloud/blob/master/requirements.txt#L1

Granted, it may see the requirement as already satisfied and not install it. I will optimistically close, expecting that to be the case.
