### ISSUE TITLE
Stop using ansible devel base image

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#237]
Now that 2.11 is out we should probably start using `quay.io/ansible/ansible-runner:stable-2.11-devel` as the base image.

**Comment by AlanCoding** [comment]
could we start tagging that as `:latest`, and then we could stop putting the tag on the value? Raised at: https://github.com/ansible/ansible-runner/pull/716

Putting in 2.11 for that constant doesn't feel like it would age well.

**Comment by AlanCoding** [comment]
For testing:

`quay.io/ansible/ansible-runner:stable-2.11-devel` should now be the same as `quay.io/ansible/ansible-runner:latest`. So we did what was said originally, effectively.

**Comment by kdelee** [comment]
lgtm, thanks
