### ISSUE TITLE
network-ee EE fails to run playbook while running with ansible-navigator

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-builder#247]
` Unhandled message from runner queue, discarded` message is received in logs while running with ansible-navigator
Command:
```
ansible-navigator run --eei quay.io/ansible/network-ee:stable-2.11 local.yaml -i $PWD/inventory --mode=stdout --ce podman --ll debug 
```

The root cause of the issue is ansible-runner fails silently while reading event data from temp file of disk https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/runner.py#L76 due to permission issues resulting in sending partial data to ansible-navigator.

The suspected root cause is the mounted user id is not the same as that of the host user
```
# host id
$ id -u
1001
```
```
# quay.io/ansible/network-ee:stable-2.11 /bin/bash (not working)
bash-4.4# id
uid=0(root) gid=0(root) groups=0(root)
```
```
# registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-20-ee-supported-rhel8:latest (working)
bash-4.4$ id
uid=1001(ganeshrn) gid=1001(runner) groups=1001(runner),0(root)
bash-4.4$
```

Can also be verified by running command (except the volume mount part) generated by ansible-runner for execution
```
$ podman run --rm --interactive --tty   --group-add=root --userns=keep-id --ipc=host   --quiet --name ansible_runner_bdf025b0-ff45-4f3d-9443-08a8d42bd07e quay.io/ansible/network-ee:stable-2.11 id 
uid=0(root) gid=0(root) groups=0(root)
```

```
 podman run --rm --interactive --tty   --group-add=root --userns=keep-id --ipc=host   --quiet --name ansible_runner_bdf025b0-ff45-4f3d-9443-08a8d42bd07e  registry-proxy.engineering.redhat.com/rh-osbs/ansible-automation-platform-20-ee-supported-rhel8:latest  id 
uid=1001(ganeshrn) gid=1001(runner) groups=1001(runner),0(root)
```

**Comment by wenottingham** [comment]
Closing this as we don't see there's anything wrong with builder here. If there's an issue with navigator launching provided EEs, we should discuss it out of band in someplace that's not a GH issue.
