### ISSUE TITLE
Ability to produce future-proof Containerfile

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#25]
A couple of scenarios of concern:

 - An execution environment spec with un-versioned collection requirement: someone builds a Containerfile with `requirements.txt` inside of its build context. Collection releases new version with new or removed python dependencies, and new images built with Containerfile will now fail to run content
 - An execution environment spec with versioned collection: a dependency of the primary collection releases a new version with changed python or system requirement, so same basic scenario happens, content may fail to run

Brainstorm of a couple of solutions:

 - Leave various un-versioned forms of requirements around, document that Containerfile is not meant to be a long-lived artifact. Establish that the container image is the product of concern, and that the Containerfile itself is intended to be intermediary, and not kept around.
   - Potentially set some kind of time-to-live, and fail the image build if a certain time has passed
 - Pin requirements of all forms, so any `requirements.txt`, `requirements.yml`, or `bindep.txt` would be processed when `ansible-builder` is ran, and do something like a `pip freeze` for every case, producing a file with pinned versions for all types of dependencies and only put that in the build context.
 - Put the installed collections into the build context, and only `ADD` them in the Containerfile, so that results of `ansible-galaxy collection install` will not give different outcomes from one build to the next

**Comment by kdelee** [comment]
> * Put the installed collections into the build context, and only `ADD` them in the Containerfile, so that results of `ansible-galaxy collection install` will not give different outcomes from one build to the next

TBH I kinda thought this was way it was going to go down but I do see point of then Containerfile is not very portable, has to go w/ whole context dir.

**Comment by AlanCoding** [comment]
Yes, but I worry that it over-simplifies the problem.

The initial implementation I'm working on is likely to knowingly violate the idea here, just to have a work-in-progress that we can make some testing progress with.

If we use ADD to solve these, then it makes more sense to package the collection `tar.gz` files in the build context, as opposed to the fully installed file structure of the collections. I filed https://github.com/ansible/ansible/issues/70429 as I was trying to define the limitations of that. It's not a home-run, it might work in some cases, but not all.

----
It's also not necessary _wrong_ to have a Containerfile that pulls in new versions. It can be desirable to use the up-to-date versions, and produce images on the fly. What if you wanted to put the build context into your project source? You should either want `ansible-builder` to pin everything, or not pin anything. You just don't want a mix of the two.

If you want everything un-pinned... then the best solution is to take all of the logic and put it into the Containerfile. In that case, maybe the Containerfile installs ansible-builder and then calls an ansible-builder command. Instead of writing a Containerfile, this command will just run the instructions directly.

That would look a whole lot like adding a flag to the collection install command, like `ansible-galaxy collection install -r requirements.yml --system-deps`.
