### ISSUE TITLE
no FROM statement found

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible-builder#260]
When attempting to build an EE, I get an error that looks like below: 
```
File ./_build/requirements.yml is already up-to-date.
File ./_build/ansible.cfg is already up-to-date.
Rewriting Containerfile to capture collection requirements
Running command:
  podman build -f ./Containerfile -t pure_test .
STEP 1: FROM quay.io/aap/ansible-automation-platform-20-ee-minimal-rhel8 AS galaxy
Error: no FROM statement found
```
Version
```
[thedoubl3j@localhost demo-ee]$ ansible-builder --version
1.0.0
```
OS/ENV
```
Fedora 34
Podman 3.2.1
```

when messing around with the execution-environment.yml file, I noticed that if I comment out the ansible.cfg key, it is able to move forward so I think the issue lies somewhere in the creation of the containerfile and or the order it expects things to be in the `execution-environment.yml` file.

**Comment by shanemcd** [comment]
That's weird. Can you paste the output of the generated Containerfile?

**Comment by sabre1041** [comment]
@shanemcd hitting the same issue. The directive to add the `ansible.cfg` file is in the incorrect location in the Containerfile

```
ARG EE_BASE_IMAGE=<base_image>
ARG EE_BUILDER_IMAGE=<builder_image>
ADD _build/ansible.cfg ~/.ansible.cfg


FROM $EE_BASE_IMAGE as galaxy
ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
USER root
...
```

**Comment by AlanCoding** [comment]
You're right, I think this is in the wrong location

https://github.com/ansible/ansible-builder/blob/devel/ansible_builder/main.py#L73

After last things got moved, I think it was not realized that the FROM was in the next step, and it should be moved down to after that.

We should also add an integration test that uses the ansible config (it can be a fast one).

**Comment by rajatguptarg** [comment]
I am facing the same issue. Following.

**Comment by shanemcd** [comment]
Should be fixed by https://github.com/ansible/ansible-builder/pull/261. 

@AlanCoding I wanted to get a fix up and ship 1.0.1 before calling it a weekend. Didn't look into adding tests. Can you add that to your list of things for next week if you have time?

**Comment by shanemcd** [comment]
Hi all. Builder 1.0.1 is up on pypi and should fix this issue. Please let us know if you run into any more problems.

**Comment by rajatguptarg** [comment]
> Hi all. Builder 1.0.1 is up on pypi and should fix this issue. Please let us know if you run into any more problems.

works fine now. Thank you.

**Comment by rajatguptarg** [comment]
Now there is another error while running the command in `Containerfile`:

```
RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
```

The output is:
```
#18 0.240 /bin/sh: ansible-builder: command not found
#18 ERROR: executor failed running [/bin/sh -c ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt]: exit code: 127
------
 > [builder 5/6] RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt:
------
executor failed running [/bin/sh -c ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt]: exit code: 127
```

The error message is `ansible-builder command not found`.

EDIT: Kinda hack. Updating the `python-builder` container to install `ansible-builder` fix the issue.

FIX:

Following line can be added
```
self.steps.append("RUN pip install -U ansible-builder")
```
 here: https://github.com/ansible/ansible-builder/blob/devel/ansible_builder/main.py#L393

**Comment by kdelee** [comment]
@rajatguptarg sounds like you might be hitting a different problem

with 1.0.1 pip installe, I can build the following `execution-environment.yml`
```
---
version: 1
ansible_config: ansible.cfg
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/aap/ansible-automation-platform-20-ee-minimal-rhel8'
  EE_BUILDER_IMAGE: 'quay.io/aap/ansible-automation-platform-20-ansible-python-base-rhel8'
dependencies:
  galaxy: requirements.yml
```
given that `requirements.yml` and `ansible.cfg` exist
