### ISSUE TITLE
Add support for test-requirements.txt

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible-builder#267]
In `amazon.aws` collection, there is a [test requirement](https://github.com/ansible-collections/amazon.aws/blob/main/test-requirements.txt) which is different than normal `requirements.txt`. 

For `network-ee` job, we require these requirements for unit tests. It seems that right now there is no way to specify `test-requirements.txt` while building the image using `ansible-builder`. 

Please suggest some alternative or add support for test-requirements.txt.

**Comment by Shrews** [comment]
@Akasurde Couldn't you just use the `additional_build_steps` section of the EE def file to install the additional requirements yourself?

**Comment by Akasurde** [comment]
@Shrews Let me check if it works for me and get back to you.

**Comment by pabelanger** [comment]
what we really should support, is the ability to build 'test-requirements.txt' atop of an execution environment image. This would mean, adding the ability to introspect to search 'test-requirement.txt' files from each collection, over the requirements.txt file.

https://github.com/ansible/network-ee/blob/main/tests/Containerfile kinda explains more what I am thinking, except we don't introspect the test requirements file, we use a global one.

**Comment by samdoran** [comment]
Is this still an issue? It seems like using `additional_build_steps` to install additional requirements would work.

**Comment by Shrews** [comment]
Since there has been no response on this issue for some time, I'm going to assume this is no longer an issue and close it.
