### ISSUE TITLE
EE_BASE_IMAGE documentation is incorrect

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible-builder#291]
https://ansible-builder.readthedocs.io/en/latest/definition.html#execution-environment-definition shows you define the base image as:

```
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'
```

However, using this gives an error:

```
Keys {'EE_BASE_IMAGE'} are not allowed in 'build_arg_defaults'.
```

**Comment by Shrews** [comment]
I am unable to reproduce this with the latest version. I tried a very simple `execution-environment.yml` file using the data you supplied:

```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'
```

The following information could help here:

- What is the version of `ansible-builder` you used (output of `ansible-builder --version`)?
- Can you provide the `execution-environment.yml` file that produced this, or a simplified version that produces the error?

**Comment by matburt** [comment]
No feedback from reporter... I also can't reproduce this.
