### ISSUE TITLE
feature request: build Multiarch images

### ISSUE THREAD

**Issue by fibbs** [ansible/ansible-builder#292]
I have been making my first steps with Ansible-builder to create a custom execution environment for an AWX installation. One big thing I noticed is that if I use ansible-builder on my Apple Silicon Mac, the resulting image will be arm64 only and not usable on my AWX install. As more and more, also servers, are going ARM nowadays, I would recommend considering using `docker buildx` instead of `docker build` to build multiarch images right away, or at least provide the necessary options to do that.
Of course, for this also the base EE images would have to be multiarch...

**Comment by Akasurde** [comment]
With Ansible Builder v3 you can specify different Base OSes which allows user to build their own images with different OSes and architectures. Going forward we are not maintaining any images on quay.io. You can check more parameters [here](https://ansible-builder.readthedocs.io/en/latest/definition/#version-3-format).

Closing this feature request. Thanks,
