### ISSUE TITLE
feature request: multiple tags on build

### ISSUE THREAD

**Issue by cloin** [ansible/ansible-builder#295]
Currently specifying multiple tags like so: `ansible-builder build -t tag1 -t tag2`, results in `docker build -f context/Dockerfile -t tag2 context`

The underlying tools support multiple tags so it would be nice if specifying multiple tags with `ansible-builder` was possible as well.

**Comment by webknjaz** [comment]
+1 on this idea! I'd also love to have it.

**Comment by MallocArray** [comment]
+1
