### ISSUE TITLE
[DOC] `ansible-builder container build|create` commands do not exist

### ISSUE THREAD

**Issue by vrubiolo** [ansible/ansible-builder#310]
First, thanks for `ansible-builder`! I am using it to virtualize our Ansible playbook environments through AWX and the idea of being able to run jobs on an individual developer workstation this way before moving them into AWX is great. The documentation is also very helpful, especially since the AWX side (at https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html) does not go into too many details about how to build custom EEs.

I am filing this ticket because I see the documentation at https://ansible-builder.readthedocs.io/en/latest/usage/#cli-usage mentions the `ansible-builder container build` command which does not exist:
```bash
$ ansible-builder container build
usage: ansible-builder [-h] [--version] {create,build,introspect} ...
ansible-builder: error: argument action: invalid choice: 'container' (choose from 'create', 'build', 'introspect')
$ ansible-builder --version
1.0.1
```

Using `ansible-builder build` instead allows the build to proceed.

The same is true for `ansible-builder container create`

Let me know if you welcome MRs, I can carve one to fix the issue once confirmed.

**Comment by Shrews** [comment]
This new CLI feature was added in https://github.com/ansible/ansible-builder/pull/279 and is not available in the `1.0` release, nor will it be backported. It seems our docs are based on the `devel` branch and not the released versions, so it is slightly ahead.

**Comment by vrubiolo** [comment]
Ok, thanks for this information, this is useful to know. I will keep that in mind when browsing the docs.

**Comment by samdoran** [comment]
The `latest` docs are based on the `devel` branch. For viewing documentation from the latest release, use the [`stable` version](https://ansible-builder.readthedocs.io/en/stable/).

**Comment by samdoran** [comment]
We could change it so the doc site defaults to showing `stable` rather than `latest`.

**Comment by vrubiolo** [comment]
Thanks @samdoran , I had missed the version selector which is very useful!
Yes, I think maybe defaulting to showing *stable* would be a good thing. This would match what you get when installing from *pip* (I am using Fedora 34). People wanting the *devel* one can always switch using the selector.

**Comment by samdoran** [comment]
I will change the docs for this project to default to showing the documentation for the stable release, not the development branch.

**Comment by samdoran** [comment]
Closing since the docs site now defaults to showing the stable version of the docs.
