### ISSUE TITLE
Private python requirements impossible to install due to outdated requirements-parser

### ISSUE THREAD

**Issue by SirUli** [ansible/ansible-builder#319]
When trying to install private python requirements the outdated library requirements-parser is in the way (Probably since it had not been 

Our requirements.txt contain a couple lines in the beginning which are allowed for pip:

```
--index-url=https://some-host.example.com/repository/pypi-proxy/simple
--extra-index-url=https://some-host.example.com/repository/custompy/simple
--trusted-host=some-host.example.com
```

[Both of the open PRs](https://github.com/davidfischer/requirements-parser/pulls) on that repo would fix parts of the required settings.

A couple Links on that:
- [requirements-parser: This project is actively seeking maintainers](https://github.com/davidfischer/requirements-parser/issues/45)
- [requirements-parser: Usage of pip directly?](https://github.com/davidfischer/requirements-parser/issues/50)

Not sure which path to go but that is currently pretty much stopping us from using ansible-builder.

**Comment by eqrx** [comment]
Hey @SirUli, sorry for the delay on this issue and thank you for the detective work. I have decided to test how dropping the dependency and would like to see if my solution fully covers you use case. 

Could you provide me a more complete reproducer? Don't worry if not I would use my local scenario but I want to be sure I do not miss anything :)

Cheers

**Comment by eqrx** [comment]
https://github.com/madpah/requirements-parser/issues/62 adds the required functionality to requirements-parser. It solves the problem in my setup. @SirUli can you confirm please?

**Comment by SirUli** [comment]
@eqrx sorry for my delayed reply. Yes now all is wonderful, this fixed the outstanding issue! Now it works, lovely :)

**Comment by SirUli** [comment]
@eqrx reopening - the issue is that they actually had not added the functionality but just are skipping everything that isn't "supported" and left https://github.com/madpah/requirements-parser/blob/master/requirements/parser.py#L76 which means that private repos stay unsupported.

So the change that happened is actually that the private repos are skipped with a Warning and everything still continues - which is a change but actually doesn't fulfill the original issue ;)

For the reproducer: Basically just add the lines from the top to any of your requirements.txt and check then during the build the requirements.txt that is generated (which actually misses the lines then).

**Comment by SirUli** [comment]
For the reproducer: Basically just add the lines from the top to any of your requirements.txt and check then during the build the requirements.txt that is generated (which actually misses the lines then).

**Comment by eqrx** [comment]
Oh wow, that makes my reproducer look a bit sad :D Thank you for looking into it!
I will (starting monday) help working on requirements-parser for this issue and look for a mitigation for you while this is in the works.

**Comment by eqrx** [comment]
@SirUli Lets wait for discussion in madpah/requirements-parser#64 and see how we can tackle this problem. Does this work for you?

**Comment by SirUli** [comment]
> @SirUli Lets wait for discussion in madpah/requirements-parser#64 and see how we can tackle this problem. Does this work for you?

Absolutely fine - currently this keeps us from adopting ansible-builder but we live also with the current situation. So no worries - this is a bit more tricky than I thought...

**Comment by maniac18** [comment]
@eqrx: Any update? I made a workaround by changing the generated Containerfile. Also the ansible-builder should implement this: https://github.com/ansible/ansible-builder/issues/211. I used it for the workaround but the PIP_OPTS parameter should also be added to the install-from-bindep script in the python-builder
