### ISSUE TITLE
Output from `build` command needs more info

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-builder#32]
ansible-buidler build seems to do something for a while but then it says Complete! Build context is at: context but this is ????? does not tell me what the image is named/tagged or how to actually find it.

I am learning that the default tag name and container runtime are defined here https://github.com/ansible/ansible-builder/blob/ec481d8c8a8dd995614aa1f46baccad4e2253715/ansible_builder/constants.py and can be overriden with these cli options:
https://github.com/ansible/ansible-builder/blob/devel/ansible_builder/cli.py#L47-L69

Would be nice if it streamed the standard out from the build so I could see what it was doing and/or print the command it was running.

For example, running `podmand build -t foo` against the context dir prints this out:
```
podman build -t foo context
STEP 1: FROM shanemcd/ansible-runner
STEP 2: ADD requirements-galaxy.yml /build/
--> Using cache 3c38d111ddb5973a7b0cf7da0c880e92a626ab1833c5f541282474e8b523069c
STEP 3: RUN ansible-galaxy role install -r /build/requirements-galaxy.yml --roles-path /usr/share/ansible/roles
--> Using cache 486039834b6973edf273357cae57aa5aad6a6f63eae662d78f08ed47dc10143a
STEP 4: RUN ansible-galaxy collection install -r /build/requirements-galaxy.yml --collections-path /usr/share/ansible/
collections
--> Using cache 8ab174613b064c74ccaf40fd38177a6bab9cd4255cf5ad2bad951a1524942b76
STEP 5: COMMIT foo
--> 8ab174613b0
8ab174613b064c74ccaf40fd38177a6bab9cd4255cf5ad2bad951a1524942b76
```

Then it could do something like:
```
podman images -a foo
REPOSITORY                        TAG      IMAGE ID       CREATED          SIZE
localhost/foo                     latest   8ab174613b06   43 minutes ago   673 MB
```
then you would see the result

**Comment by beeankha** [comment]
@kdelee agreed, and it's is one of the to-dos listed here: https://github.com/ansible/ansible-builder/issues/12#issuecomment-649786963

**Comment by kdelee** [comment]
https://github.com/ansible/ansible-builder/pull/35 merged and now output should show from underlying commands

**Comment by kdelee** [comment]
Tested locally and I am seeing the additional informaiton from underlying commands streaming through, thanks!
