### ISSUE TITLE
Option to disable the dnf update from the assemble script 

### ISSUE THREAD

**Issue by raedrizk** [ansible/ansible-builder#339]
The assemble script runs a dnf update by default during the ee build. It would be useful to have the default behavior to not run the update (for consistency, disconnected environments...etc), and instead have an argument to update if desired.

**Comment by Shrews** [comment]
The `assemble` script is not contained within `ansible-builder`, so this would need to be first handled in the repo where the `assemble` script lives (see [python-builder-image](https://github.com/ansible/python-builder-image)). If that repo chooses to support such an option, we could then consider something in `ansible-builder`. I suggest opening an issue there.
