### ISSUE TITLE
Document Container Image logic

### ISSUE THREAD

**Issue by ryanmerolle** [ansible/ansible-builder#347]
It seems there is only 1 tag for the [ansible builder container image](https://quay.io/repository/ansible/ansible-builder?tag=latest&tab=tags), and its latest.

I was thinking latest would be `1.0.1`, but pip is saying it is using `1.0.0.0a3.dev99`.

- What is the logic behind the docker image creation?
- Can we improve that documentation?
- Does it make sense to introduce 2 different tags? 1 for the latest stable pypi release and 1 for the latest dev release?

**Comment by ryanmerolle** [comment]
To record what @Shrews said in chat on the ticket:

> as for the builder images, i suspect the same issues as the runner images, but haven't looked yet

Not trying to @ someone for work, just documenting if someone comes across this ticket.

He is referring to ansible/ansible-runner#990

**Comment by sivel** [comment]
Going to close this out.  We are no longer producing, nor maintaining, the builder container images.  It is recommended to use ansible-builder 3.0, with a v3 schema, to build an EE without need of a pre-configured base image.
