### ISSUE TITLE
Ansible module for ansible-builder

### ISSUE THREAD

**Issue by jangel97** [ansible/ansible-builder#358]
Hi,

My team and me are using ansible-builder in our Ansible Playbooks to build Container Images for the Ansible Automation Platform Execution Environments. In order to achieve this, we are using ansible-builder via command module https://github.com/redhat-cop/ee_utilities/blob/main/roles/ee_builder/tasks/main.yml#L19.

Would it make sense to work on an Ansible module that wraps around the ansible-builder script? And it can support idempotency, different options, and so on.

If so, I would like to work on this, it looks like an interesting work. But, what namespace/collection do you think this module should belong to?

Thanks in advance,

**Comment by Shrews** [comment]
Hi,

You are certainly welcome to develop such a module for your personal use, but it certainly isn't something we'd consider maintaining within this repo. I'm failing to see any advantage of a separate module for running this command., and I have no suggestions on where such a module should live, but that shouldn't stop you from developing your own if you find it useful.

Best of luck.

**Comment by Shrews** [comment]
Just an additional thought, you might ask in the [Ansible Community channels](https://docs.ansible.com/ansible/latest/community/communication.html#real-time-chat) to see if there are any like-minded folks who may also like to have such a module. They can probably direct you to the proper collection (if one exists) for such a module, or assist you in creating one.  The #ansible-community IRC channel is the first place I would ask.
