### ISSUE TITLE
RFE Providing sample configuration files with builder

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible-builder#362]
ansible-builder requires a few different configuration files to do useful things, but the install doesn’t provide anything to start with.  Might it be possible to provide some sample files with some commented-out options for customers to start with?

**Comment by Shrews** [comment]
Not an unreasonable request. A fairly simple `demo` directory, like we have in the [runner repo](https://github.com/ansible/ansible-runner/tree/devel/demo), would suffice.
