### ISSUE TITLE
Version container images in quay.io!

### ISSUE THREAD

**Issue by jtudelag** [ansible/ansible-builder#367]
Hey,

It would be great to have images versioned in quay.io! Currently is only "latest" tag: https://quay.io/repository/ansible/ansible-builder?tab=tags

Thanks a lot!

**Comment by eqrx** [comment]
Hey, that is a good issue, we will definitely take care of that but I can't tell you when it is going to come to that :(

**Comment by daneov** [comment]
@eqrx Is there something I can do to help with this? We can pin it by sha in the meantime, but since it has been 4 months the image has been updated I think there'll be some fixes/features missing in there :)

**Comment by eqrx** [comment]
hey @daneov, Thank you for asking and the support! One of us is currently reworking the image publishing of builder and actual versioning should be included in it. So I would say: Stay tuned, actual tags should come soonish:)

**Comment by sivel** [comment]
I'm going to go ahead and close this.  We're no longer producing an upstream builder image. Users should use a `v3` `execution-environment.yml` and build an execution environment to meet their needs from a vanilla base image, or other appropriate base image on the architecture they need.

ansible-builder 3.0.0rc1 has been released and will see a GA release in the near future.

See https://ansible-builder.readthedocs.io/en/latest/definition/
