### ISSUE TITLE
quay.io/ansible/ansible-builder:latest has no aarch64 platform

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-builder#373]
Apparently the runner image from `quay.io/ansible/ansible-builder:latest` is not dual-arch x64/aarch64 and that is a serious issue as we would expect more and more users to user aarch64 (Apple Silicon being a major driver).

Directly impacts @ansible/devtools creator-ee project.

Related: https://github.com/ansible/ansible-runner/issues/1046
Blocks: https://github.com/ansible/creator-ee/issues/7

**Comment by shanemcd** [comment]
JFYI we just merged a PR for receptor that shows how to do architecture emulation with qemu and docker buildx: https://github.com/ansible/receptor/pull/652

**Comment by sivel** [comment]
I'm going to go ahead and close this.  We're no longer producing an upstream builder image. Users should use a `v3` `execution-environment.yml` and build an execution environment to meet their needs from a vanilla base image, or other appropriate base image on the architecture they need.

ansible-builder 3.0.0rc1 has been released and will see a GA release in the near future.

See https://ansible-builder.readthedocs.io/en/latest/definition/
