### ISSUE TITLE
ansible-builder doesn't work under Python 3.6 nor 3.7

### ISSUE THREAD

**Issue by keachi** [ansible/ansible-builder#379]
# Summary

I tried to use ansible-builder with a Python 3.6 environment (default Python version on RHEL 8) and couldn't start ansible-builder. It fails to start in a very early step.
The error message is this:
```
$ ansible-builder --version
ValueError: unknown action "extend"
```

I tested the following Python versions:
* 3.6.8 -> failed
* 3.7.13 -> failed
* 3.10.4 -> works as expected

Python 3.6.8 worked with ansible-builder 1.0.1. Because it wasn't a major version increase, I expect that it should still work on Python 3.6.8. And I didn't found any information about supported Python versions by ansible-builder.

# Expected behaviour

Ansible-builder should return the current version:
```
$ ansible-builder --version
1.1.0
```

# Environment
```
$ python --version
Python 3.6.8
$ pip list | grep ansible-builder
ansible-builder     1.1.0
```

**Comment by Shrews** [comment]
The current minimum version of Python supported by `ansible-builder` 1.1.0 is 3.8.

**Comment by Shrews** [comment]
We should document this in our documentation, so I've left this open for someone to add that enhancement.
