### ISSUE TITLE
Command Line Options needed for role installation

### ISSUE THREAD

**Issue by monorailpilot** [ansible/ansible-builder#392]
Currently, ansible builder can pass arguments to ansible-galaxy's collection installation process using the following in execution-environment.yml.  

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"

There is no similar ANSIBLE_GALAXY_CLI_ROLE_OPTS however, which makes it impossible to do things such as disable SSL checking or get verbose output.

**Comment by eqrx** [comment]
Hey, thank you for the issue! We do not have `ANSIBLE_GALAXY_CLI_ROLE_OPTS` since builder does not install roles, only collections. What exact use case do you have? :)

**Comment by monorailpilot** [comment]
> Hey, thank you for the issue! We do not have `ANSIBLE_GALAXY_CLI_ROLE_OPTS` since builder does not install roles, only collections. What exact use case do you have? :)

So Ansible Builder is creating a container file that contains these two lines, so I believe the statement about not installing roles is incorrect.  It looks like steps.py line 75 implements this.

`RUN ansible-galaxy role install -r requirements.yml --roles-path /usr/share/ansible/roles`
`RUN ansible-galaxy collection install $ANSIBLE_GALAXY_CLI_COLLECTION_OPTS -r requirements.yml --collections-path /usr/share/ansible/collections
`

An example use case is that lacking access to galaxy/automation hub or similar service, roles can be packaged into the execution environment instead of being combined with code.  This allows roles to be maintained in a single execution environment that support numerous playbooks that require the role, instead of having to download and maintain the tarball in multiple code bases.
