### ISSUE TITLE
Ansible builder failing on sanitize when trying to use several collections

### ISSUE THREAD

**Issue by jompins** [ansible/ansible-builder#399]
Hi all,
I just recently noticed that Ansible-Builder seems to have issues with some modules we're using. They were all running fine when we last used those modules in previous versions but somehow they were updated and now the Ansible-Builder complains about missing requirements.txt. This applies to all the dellemc modules on Galaxy, but I'm not sure if others are also affected. The AWX one installs fine and the builder doesn't complain

Installing the modules manually works fairly decent, also resolving the Python requirements. Is there any workaround for this? The requirements.txt is not really necessary, since we are resolving them anyway with the builder. Were there any breaking changes lately? 

```
`unning command:
  docker build -f context/Dockerfile -t /awx-test-col context
...showing last 20 lines of output...
Starting collection install process
Downloading https://galaxy.ansible.com/download/dellemc-powerscale-1.6.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-1e7bjp49o/tmp9q0c9aik/dellemc-powerscale-1.6.0-xrqboz8p
Installing 'dellemc.powerscale:1.6.0' to '/usr/share/ansible/collections/ansible_collections/dellemc/powerscale'
dellemc.powerscale:1.6.0 was installed successfully
Downloading https://galaxy.ansible.com/download/awx-awx-21.2.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-1e7bjp49o/tmp9q0c9aik/awx-awx-21.2.0-etajuhm9
Installing 'awx.awx:21.2.0' to '/usr/share/ansible/collections/ansible_collections/awx/awx'
awx.awx:21.2.0 was installed successfully
Removing intermediate container b380ce11f808
 ---> 43ab02772806
Step 10/19 : FROM $EE_BUILDER_IMAGE as builder
 ---> b0348faa7f41
Step 11/19 : COPY --from=galaxy /usr/share/ansible /usr/share/ansible
 ---> e0ac7734d4b1
Step 12/19 : ADD _build/requirements.txt requirements.txt
 ---> 818aac3596ce
Step 13/19 : RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
 ---> Running in 868162b115f2
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ansible/collections/ansible_collections/dellemc/powerscale/../requirements.txt'
Expected requirements file not present at: /usr/share/ansible/collections/ansible_collections/dellemc/requirements.txt
The command '/bin/sh -c ansible-builder introspect --sanitize --user-pip=requirements.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt' returned a non-zero code: 1

An error occured (rc=1), see output line(s) above for details.
`
```

**Comment by Akasurde** [comment]
@jompins Thanks for reporting this issue. Could you please provide `ee.yml` and `requirements.yml` files to reproduce this issue? Thanks.

**Comment by Akasurde** [comment]
@jompins After debugging a bit, I found that `dellemc.powerscale` collection added `meta/execution-environment.yml` file with [1.6.0 release](https://github.com/dell/ansible-powerscale/commit/72b1b848cc59caa04c2cde3392d50ab087aec7ba). But Python dependency `dependencies` mentioned in [execution-environment.yml](https://github.com/dell/ansible-powerscale/blob/0ee86eaac41f26ddd057ac2c688e4f85dc78432f/meta/execution-environment.yml#L5) should be 

```yml
...
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
...
```

instead of 

```yml
...
dependencies:
  galaxy: ../requirements.yml
  python: ../requirements.txt
...
```

**Comment by Akasurde** [comment]
The path can be relative to the execution-environment.yml directory. https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html#ansible-galaxy-dependencies

**Comment by jompins** [comment]
Hi @Akasurde  thanks for debugging this! I feared it was a collection issue all along. I will close our issue here and forward this to the DellEMC developers!
