### ISSUE TITLE
restrict min Python version when installing

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible-builder#407]
According to #379 and #381, ansible-builder 1.1.0 needs Python 3.8  or higher.

Not only documentation, I would like to restrict when installing.

Like this:  https://github.com/ansible/ansible/blob/v2.13.2/setup.cfg#L39

**Comment by kuznetsovkk** [comment]
```
[root@host ~]# update-alternatives --display python
python - status is manual.
 link currently points to /usr/bin/python3.8
/usr/libexec/no-python - priority 404
 slave unversioned-python: (null)
 slave unversioned-python-man: /usr/share/man/man1/unversioned-python.1.gz
/usr/bin/python3 - priority 300
 slave unversioned-python: /usr/bin/python3
 slave unversioned-python-man: /usr/share/man/man1/python3.1.gz
/usr/bin/python3.8 - priority 208
 slave unversioned-python: /usr/bin/python3.8
 slave unversioned-python-man: /usr/share/man/man1/python3.8.1.gz
Current `best' version is /usr/libexec/no-python.

[root@host ~]# python --version
Python 3.8.12

[root@host ~]# ansible-builder
ValueError: unknown action "extend"

[root@host ~]# rpm -qf /usr/bin/python3.8
python38-3.8.12-1.module+el8.6.0+12642+c3710b74.x86_64
```
What am I doing wrong?

**Comment by Akasurde** [comment]
@kuznetsovkk https://github.com/ansible/ansible-builder/issues/412#issuecomment-1227513512

**Comment by kuznetsovkk** [comment]
> @kuznetsovkk [#412 (comment)](https://github.com/ansible/ansible-builder/issues/412#issuecomment-1227513512)

I already use python 3.8 as you can see. Or not?

**Comment by kuznetsovkk** [comment]
> > @kuznetsovkk [#412 (comment)](https://github.com/ansible/ansible-builder/issues/412#issuecomment-1227513512)
> 
> I already use python 3.8 as you can see. Or not?

ok, I fixed this problem with:

```
$ update-alternatives --config python3

There are 2 programs which provide 'python3'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/bin/python3.6
   2           /usr/bin/python3.8

Enter to keep the current selection[+], or type selection number: 2
```

But now i have another problem:

```
$ ansible-builder build
Traceback (most recent call last):
  File "/usr/local/bin/ansible-builder", line 5, in <module>
    from ansible_builder.cli import run
ModuleNotFoundError: No module named 'ansible_builder'
```

**Comment by kuznetsovkk** [comment]
> But now i have another problem:
> 
> ```
> $ ansible-builder build
> Traceback (most recent call last):
>   File "/usr/local/bin/ansible-builder", line 5, in <module>
>     from ansible_builder.cli import run
> ModuleNotFoundError: No module named 'ansible_builder'
> ```

Ok, fixed with:
`/usr/bin/pip3.8 install ansible-builder`
