### ISSUE TITLE
ERROR: Double requirement given: pyvmomi

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible-builder#408]
### issue

ansible-builder fails with this error.

```
+ pip3 install --cache-dir=/output/wheels -r /tmp/src/requirements.txt
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
ERROR: Double requirement given: pyvmomi (from -r /tmp/src/requirements.txt (line 5)) (already in pyVmomi>=6.7 (from -r /tmp/src/requirements.txt (line 1)), name='pyvmomi')
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1

An error occured (rc=1), see output line(s) above for details.
```

references: #45, #351

### environment

```
# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)

# dnf list installed | grep ansible-builder
ansible-builder.noarch                        1.1.0-3.el8ap                               @ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms

# ansible-builder --version
1.1.0

# podman --version
podman version 4.1.1
```

### step to reproduce

I created definitions files as below.

1. execution-environment.yml 

```
---
build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-29-rhel8:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
```

2. requirements.txt

```
ansible==2.9.27
psutil
pyvmomi
```

3. requirements.yml

```
---
collections:
- name: community.vmware
```

After that, I downloaded the images in advance.

```
# podman images
REPOSITORY                                                               TAG         IMAGE ID      CREATED        SIZE
registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8     latest      e992a75cc062  8 days ago     1.45 GB
registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8       latest      0ba765fbe331  8 days ago     286 MB
registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8  latest      5f854afaaaa4  8 days ago     311 MB
registry.redhat.io/ansible-automation-platform-22/ee-29-rhel8            latest      45fa22cc1c56  8 days ago     805 MB
```

I performed the ansible-builder command.

```
# ansible-builder build -f execution-environment.yml -v 3 -t localhost/my-custom-ee-29
```

I will attach the whole output.

### workaround

When I commented out the line in requirements.txt, it worked as expected.

```
# cat requirements.txt 
ansible==2.9.27
psutil
#pyvmomi
```

I guess when the `pyvmomi` is already installed in the EE_BASE_IMAGE, it seems the builder (introspect?) didn't calculate the duplication in the procedure.

### background

My customer wants to migrate the virtual environments from Ansible Tower 3.8 to Ansible Automation Platform 2.2 according to this step described in this product documentation.

https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.2/html/red_hat_ansible_automation_platform_upgrade_and_migration_guide/upgrading-to-ees

However the output of `awx-manage export_custom_venv /path/to/venv` cannot be applied to `ansible-builder` command like this issue, it makes confused.

**Comment by sugitk** [comment]
Whole output of the ansible-builder command.

[issue.txt](https://github.com/ansible/ansible-builder/files/9355545/issue.txt)

**Comment by Akasurde** [comment]
@sugitk Thanks for reporting this issue.
