### ISSUE TITLE
 Implement Custom Verbosity Level

### ISSUE THREAD

**Issue by beeankha** [ansible/ansible-builder#41]
Allow user to set a custom verbosity level using `-v` or `--verbosity` when running builder CLI commands.  

This work should get done _after_ a lot of the other `ansible-builder` issues have been completed, since we want to know exactly _what_ to be verbose about.

**Comment by shanemcd** [comment]
I think we may have a use for this now. I'm not sure if we want to show the `print` statements in https://github.com/ansible/ansible-builder/pull/108/files all the time.

**Comment by beeankha** [comment]
To do:
- [x] Set logger levels via specified verbosity
- [ ] Error out if non-available verbosity is selected 
- [x] Try to set up a system that assigns message color according to verbosity level
- [ ] Add info to documentation

**Comment by shanemcd** [comment]
Implemented in https://github.com/ansible/ansible-builder/pull/112
