### ISSUE TITLE
Cannot inject environment variables to set token values that ansible-galaxy should recognize

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible-builder#410]
[Documentation](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#configuring-the-ansible-galaxy-client)  for `ansible-galaxy` states:

```
As well as defining these server options in the ansible.cfg file, you can also define them as environment variables.
The environment variable is in the form ANSIBLE_GALAXY_SERVER_{{ id }}_{{ key }} where {{ id }} is the upper case form of the server identifier and {{ key }} is the key to define.
For example I can define token for release_galaxy by setting ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_TOKEN=secret_token.
```

There should be a supported way to inject those env vars into the build phase so that I do not need to create a static `ansible.cfg` file containing the token values. Currently the only way to pass the token values for each galaxy server is by creating the static `ansible.cfg` with those values which is then copied into the `context/_build` folder.  An alternative is leveraging the `envsubst < ansible.cfg.template > ansible.cfg` command to substitute strings to generate the same static file, however this seems a workaround.

Leveraging build args did not work since the args are placed in the wrong phase.

**Comment by Akasurde** [comment]
With Ansible Builder v3, you can do this -

```
additional_build_steps:
  prepend_galaxy:
    - ENV ANSIBLE_GALAXY_SERVER_<SERVER_NAME>_GALAXY_TOKEN=secret_token
    - ENV ANSIBLE_GALAXY_SERVER_<SERVER_NAME>_GALAXY_URL=https://my_galaxy_server.com
```

**Comment by Akasurde** [comment]
@ansiblejunky Can you please try this with Ansible Builder v3 schema and let us know if it works for you? Thanks,

**Comment by Shrews** [comment]
Closing this as I've sinced tested this successfully with `ansible-builder` 3.0 and using ENV vars for Automation Hub.

If you encounter any bugs using 3.0, please feel free to submit a new issue.
