### ISSUE TITLE
Run ASSEMBLE Step adds back in default repos

### ISSUE THREAD

**Issue by trippinnik** [ansible/ansible-builder#417]
I am use a base image with the repos for our internal artifactory because I cannot use internet repos.  When this runs it still uses default internet repos no matter what I do.  I can't build because of this ...

[2/3] STEP 6/6: RUN assemble
++ source /etc/os-release
+++ NAME='CentOS Stream'
+++ VERSION=8
+++ ID=centos
+++ ID_LIKE='rhel fedora'
+++ VERSION_ID=8
+++ PLATFORM_ID=platform:el8
+++ PRETTY_NAME='CentOS Stream 8'
+++ ANSI_COLOR='0;31'
+++ CPE_NAME=cpe:/o:centos:centos:8
+++ HOME_URL=https://centos.org/
+++ BUG_REPORT_URL=https://bugzilla.redhat.com/
+++ REDHAT_SUPPORT_PRODUCT='Red Hat Enterprise Linux 8'
+++ REDHAT_SUPPORT_PRODUCT_VERSION='CentOS Stream'
++ echo centos
+ RELEASE=centos
+ PKGMGR=
+ PKGMGR_OPTS=
+ '[' -z ']'
+ PKGMGR=/usr/bin/dnf
+ '[' -f /usr/bin/microdnf ']'
+ mkdir -p /output/bindep
+ mkdir -p /output/wheels
+ mkdir -p /tmp/src
+ cd /tmp/src
+ /usr/bin/dnf update -y
CentOS Stream 8 - AppStream                     1.6 MB/s |  25 MB     00:15    
CentOS Stream 8 - BaseOS                         18 MB/s |  25 MB     00:01    
CentOS Stream 8 - Extras                         47 kB/s |  18 kB     00:00    
CentOS Stream 8 - PowerTools                    2.3 MB/s | 5.0 MB     00:02    
Extra Packages for Enterprise Linux Modular 8 - 1.1 MB/s | 733 kB     00:00

**Comment by eqrx** [comment]
Sorry, we do not have a good solution for disconnected environments right now, but we will look into it!

**Comment by trippinnik** [comment]
That must be pretty common. I managed to get it working with some guesswork
but a Dockerfile with requirements would be easier to work with

**Comment by ryanmerolle** [comment]
It is something I have brought up last year in one of the associated repos (python-base or here) and on irc/slack.

You can either take the generated Dockerfile and rip out items like assemble or you can build on a machine with access to the internet.

I really cannot complain here given I am using OSS for free, but it is an annoying quality of life item with maintaining ansible EEs.

**Comment by nitzmahone** [comment]
Closing- this issue is resolved by the new builder 3.0 features, since all intermediate build stages are directly based off the base image.
