### ISSUE TITLE
RFE Add a label to indicate the image is an execution environment

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-builder#424]
ansible-navigator needs to distiguish between execution enviroments and other images. It currently uses the WORKDIR to make this determination which is probably not reliable and could lead to false positives.

https://github.com/ansible/ansible-navigator/issues/454

**Comment by Akasurde** [comment]
@cidrblock Thanks for the RFE. Can you please check if this works for you - https://github.com/ansible/ansible-builder/blob/b3a13aae2310bf7d8e9f0d31e4d37259c4dd7f39/ansible_builder/main.py#L324?

**Comment by cidrblock** [comment]
oh, that's new :)  I'm sure it will work...... ty, will report back

**Comment by cidrblock** [comment]
I totally missed this https://github.com/ansible/ansible-builder/issues/286  sorry

**Comment by Akasurde** [comment]
ah! no issues.

**Comment by cidrblock** [comment]
it's wonderful. TY
