### ISSUE TITLE
Build function should be able to inject files

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible-builder#426]
I want to create execution environments but provide internal root CA certificates as part of the EE. As far as I can tell, the only way to do this is to add the correct shell commands for adding the file to the container and updating the CA certificate list in the `prepend` section of the `execution-environment.yml` file, then run `ansible-builder create`, copy the certificate into that directory, and then do a `podman build`.

What I'd like to see is an argument to `ansible-builder build` (and perhaps in `execution-environment.yml`) which would look something like this: `ansible-builder build --copy-file certs/example.com.crt...` so when it builds it'll automatically copy that file into the `context` directory.

**Comment by Akasurde** [comment]
@kbreit Thanks for reporting this feature. This is already in pipeline. You can track it here - https://github.com/users/nitzmahone/projects/1

**Comment by kbreit** [comment]
Thanks @Akasurde. I ran into this limitation again today. Do you have any guidance on when the functionality is expected?

**Comment by Shrews** [comment]
The new builder is expected in the May-ish time frame (no hard date yet). There is a feature that should solve this that will allow for adding any file to the build context  All of the the 2.0 features will appear [in this PR](https://github.com/ansible/ansible-builder/pull/411) as they are developed. The feature you need is in active development and should appear in that main PR "any day now".
