### ISSUE TITLE
Ansible version 7.2.0 is not working on ansible builder image (latest)

### ISSUE THREAD

**Issue by NikKumar811** [ansible/ansible-builder#445]
While installing ansible with **7.2.0** version its not able to install the ansible package as ansible builder image is having the lower version of python i.e **3.8.12**, but when i updated the packages to latest version in builder image it worked fine

**When Python3.9 can be updated in ansible-builder image**

ERROR: Ignored the following versions that require a different python version: 7.0.0 Requires-Python >=3.9; 7.0.0a1 Requires-Python >=3.9.0; 7.0.0a2 Requires-Python >=3.9; 7.0.0b1 Requires-Python >=3.9; 7.0.0rc1 Requires-Python >=3.9; 7.1.0 Requires-Python >=3.9; 7.2.0 Requires-Python >=3.9

**Comment by Shrews** [comment]
Hello,

Thanks for your report.

We are not currently updating the builder images and, as of now, do not have plans to do so in the future. We are working on a newer version of builder that will allow folks to more easily create their own images with any combination of Ansible, python, runner, etc., that they need. We currently have no ETA for this new version, but we are actively working on it now.
