### ISSUE TITLE
License information not displaying in PyPi metadata.

### ISSUE THREAD

**Issue by buckeye43210** [ansible/ansible-builder#451]
The license information is missing from PyPi metatdata. This is blocking an automated process to pull ansible-navigator into our internal repo.

Dependency: PYPI - ansible-builder==1.2.0
  RejectReasons (1)
    RejectReason:   ########-####-####-####-############
      Type:   NO_LICENSES_FOUND
Dependency: PYPI - ansible-runner==2.3.2
  RejectReasons (1)
    RejectReason:   ########-####-####-####-############
      Type:   NO_LICENSES_FOUND

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible-builder/pull/449
