### ISSUE TITLE
Determine default upstream/downstream USER/WORKDIR/homedir behavior

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible-builder#463]
Currently, builder 3.0 is defaulting to `USER root`, and no `WORKDIR` (which ends up being `/`) - this causes various issues when the container is run as an arbitrary non-existent non-root user under some container runtimes. The ansible-runner container base images (and some downstream derivatives) used various `ENTRYPOINT` script magic to paper over these issues, but at the cost of hardcoded/broken homedirs and a number of other issues. The need for these tweaks has significantly decreased now that runner no longer requires knowledge of the container user's homedir.

I'm guessing we're going to at least need to set `WORKDIR` to something like `/ansible-ee` or whatever that's `root/root` and `rwx` for the `root` group to accommodate container runtimes that want to run it as arbitrary bogus UIDs. Permissions on `/` set at build-time don't appear to be preserved in the final container image, at least under podman, so with the default `WORKDIR` of `/`, runtime-injected users that use `WORKDIR` as `HOME` are non-functional.

Need to get an actual documented set of requirements on this one to be sure we can cover all the bases.

**Comment by shanemcd** [comment]
The entrypoint was also setting `ANSIBLE_CALLBACK_PLUGINS` and `ANSIBLE_STDOUT_CALLBACK` - these are important variables needed to make EEs work with AWX.

**Comment by nitzmahone** [comment]
Runner already hardcodes the stdout callback and injects `awx_display` plugin at runtime (now sans volume mount to user homedir). The majority of the entrypoint script was dealing with the "homedir for runtime-injected UID" issue and hardcoding `$HOME`, which should no longer be necessary unless CRI-O is doing something significantly different from podman and docker in that case. We do still need to solve this current issue, since podman and docker both use `WORKDIR` as the injected homedir in `/etc/passwd` for the anonymous UID case, but I think in general we're nearly all the way to not requiring a custom entrypoint script.

**Comment by shanemcd** [comment]
I've been talking with nitz directly but capturing here for posterity. 

> Runner already hardcodes the stdout callback and injects awx_display plugin at runtime (now sans volume mount to user homedir).

TIL! Awesome.

> We do still need to solve this current issue, since podman and docker both use WORKDIR as the injected homedir in /etc/passwd for the anonymous UID case

Unfortunately only podman does this as far as I can tell. Both Docker and CRI-O _don't_ do this.
