### ISSUE TITLE
Package data files are not included when installed with source files without .git

### ISSUE THREAD

**Issue by simaishi** [ansible/ansible-builder#482]
The bash files added to `_target_scripts` directory in #411 don't get included when installed from source with git info stripped out (we set `PBR_VERSION=xxx` during build) as pbr won't be able to generate the file list.

This can be reproduced by running `PBR_VERSION=xxx python3 setup.py build` without .git directory.

**Comment by simaishi** [comment]
cc @sivel @nitzmahone

**Comment by Akasurde** [comment]
resolved_by_pr #483
