### ISSUE TITLE
`setuptools_scm` switch broke PyPI metadata

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible-builder#532]
Looks like we'll have to add some metadata stuff or dynamic setuptools directives to `setup.cfg`  - we lost it all in the cutover to `setuptools_scm`, eg:  https://pypi.org/project/ansible-builder/3.0.0/

**Comment by ssbarnea** [comment]
I can confirm this bug, no readme, no metadata. Probably moving them to pyproject.toml will sort them out. DevTools removed setup.cfg file few months back.

**Comment by nitzmahone** [comment]
(the fix has been merged, but won't appear on PyPI until we do a 3.0.1 release, which I don't imagine will be too long in the making :wink: )
