### ISSUE TITLE
ansible-builder fails because requirements.txt is missing for ibm.ibm_zos_cics collection

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible-builder#533]
while using ansible-builder build command to build a Execution Environment for ibm_zos_cics collection, the following error occurs:

```
#17 [builder 4/5] RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
#17 sha256:be90875e3d1275789fbd93acd07d394ea933c266f98c37c278030d82bf999900
#17 0.644 Expected requirements file not present at: /usr/share/ansible/collections/ansible_collections/ibm/ibm_zos_cics/requirements.txt
#17 0.644 FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ansible/collections/ansible_collections/ibm/ibm_zos_cics/requirements.txt'
#17 ERROR: executor failed running [/bin/sh -c ansible-builder introspect --sanitize --user-pip=requirements.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt]: exit code: 1

#7 [stage-2 3/7] RUN ansible-galaxy collection install ibm.ibm_zos_cics
#7 sha256:251f4f3cb1489fa0a66c577c2d0726a6abc857c3d396a8ad6dd56042a03b75d2
#7 CANCELED
```

requirements.yml file has the latest version of ibm_zos_cics collection:
```
---
collections:
  - name: ibm.ibm_zos_cics
    version: 1.0.4
```

The collection:
https://github.com/ansible-collections/ibm_zos_cics

Not sure if this is an issue with ansible-builder or the collection itself, but posting this bug here too. 
Original bug on collection is [here](https://github.com/ansible-collections/ibm_zos_cics/issues/112)

ansible-builder version 1.2.0

**Comment by Akasurde** [comment]
@ansiblejunky Thanks for reporting this. Could you please provide EE definition file used for building this EE? Thanks.

**Comment by Akasurde** [comment]
@ansiblejunky `ibm.ibm_zos_cics` collection 1.0.4 is built without `requirements.txt` ([this line](https://github.com/ansible-collections/ibm_zos_cics/blob/b74a37de6f7067dfe8fb8755fc9485e80a96d1d2/galaxy.yml#L60) is excluding it while `ansible-galaxy collection build` command). This is not a builder issue. Let me know if you feel the same. 

Thanks,

**Comment by ansiblejunky** [comment]
When I git clone the collection locally, I see the requirements.txt in the root folder.
However, when I use ansible-galaxy collection install that file doesn't exist locally in the installed location. In fact, the following files do not exist anymore:
* requirements.txt
* bindep.txt
* galaxy.yml

The `meta` folder exists.

This issue is happening for both `ibm` collections (core, cics).

**Comment by sivel** [comment]
That is a result of the collection explicitly stating that the artifact that they publish to galaxy should not contain the requirements.txt.  The collection will need to be updated, and the `build_ignores` removed.  Even if you state you want to install the collection from git, the process is to build the artifact first, then install, which will still strip the necessary files.

**Comment by sivel** [comment]
Going to close this, since it's not an issue with ansible-builder.
