### ISSUE TITLE
Checks failing when building a package for openSUSE with python3.10 or 3.11

### ISSUE THREAD

**Issue by johanneskastl** [ansible/ansible-builder#534]
I am packaging ansible-builder for openSUSE. The %checks for 1.2.0 went fine (leaving aside those using podman/docker, which do not work in the build environment as podman is not installed. Or rather: even if podman were installed, it would not have connectivity to pull images etc.).

With 3.0.0, I noticed some new errors:

- test_v3_complete
- test_ansible_check_is_skipped
- test_missing_ansible
- test_missing_runner

If I understand the errors correctly, those fail as ansible-builder is called using podman as container runtime, which fails (as it is not available). So I take it that those can be safely ignored in our build environment?

Thew full build log can be found here:
https://paste.opensuse.org/pastes/0e750bb17188

**Comment by Akasurde** [comment]
@johanneskastl Our tests are designed to be run via `tox` which properly sets up the test environment. Please refer https://github.com/ansible/ansible-builder/blob/devel/CONTRIBUTING.md#linting-unit-and-integration-tests for more information. Closing this as any one of the container runtimes is required for tests to run.
