### ISSUE TITLE
ansible-builder hardcodes the package manager

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible-builder#540]
While building an EE in a RHEL8 based base image I am seeing this error:

```
/output/scripts/assemble: line 75: /usr/bin/dnf: No such file or directory
```

Further investigation of a `ansible-builder create` output shows the `Containerfile` includes this `ARG PKGMGR="/usr/bin/dnf"`. This needs a microdnf setup so I believe this is breaking it.

ansible-builder 3.0.0

**Comment by kurokobo** [comment]
See  the `package_manager_path` option: https://ansible-builder.readthedocs.io/en/stable/definition/

**Comment by Shrews** [comment]
As stated above, there is a new EE configuration option to set the package manager.

```
options:
    package_manager_path: /usr/bin/microdnf
```

Closing.
