### ISSUE TITLE
ansible-builder instorspect: how is supposed to work?

### ISSUE THREAD

**Issue by Andersson007** [ansible/ansible-builder#547]
Following https://ansible-builder.readthedocs.io/en/stable/collection_metadata/ I was going to run `introspect` against a collection with requirements but got nothing.

```
$ ansible-builder --version
3.0.0
```

I did:
```
[student@fedora03 ~]$ ansible-builder introspect --sanitize -v3 .ansible/collections/community/docker/
# Sanitized dependencies for .ansible/collections/community/docker/
---
python: []
system: []
```
It contains `meta/execution-environment.yml` and requirements in a corresponding file:
```
[student@fedora03 ~]$ cat .ansible/collections/community/docker/meta/execution-environment.yml
---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

version: 1
dependencies:
  python: meta/ee-requirements.txt
  system: meta/ee-bindep.txt

[student@fedora03 ~]$ 
[student@fedora03 ~]$ cat .ansible/collections/community/docker/meta/ee-requirements.txt 
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

docker
urllib3
requests
paramiko
```
Ok, copied `ee-requirements.txt` to the collection's root dir but it produces the same result - doesn't see the requirements:
```
[student@fedora03 ~]$ cp .ansible/collections/community/docker/meta/ee-requirements.txt .ansible/collections/community/docker/requirements.txt
[student@fedora03 ~]$ 
[student@fedora03 ~]$ ansible-builder introspect --sanitize -v3 .ansible/collections/community/docker/
# Sanitized dependencies for .ansible/collections/community/docker/
---
python: []
system: []

```
Is it a bug? I would expect to see at least `docker` under the `python` requirements

**Comment by Shrews** [comment]
You need to pass `introspect` the folder where installed collections live. From `ansible-builder introspect -h`:

```
positional arguments:
  folder                Ansible collections path(s) to introspect. This should have a folder named ansible_collections inside of it.
```

**Comment by Andersson007** [comment]
> You need to pass introspect the folder where installed collections live. From ansible-builder introspect -h:

@Shrews the folder was passed
```
ansible-builder introspect --sanitize -v3 .ansible/collections/community/docker/
```

**Comment by Andersson007** [comment]
if i put it in `ansible_collections/community/docker/` in my home directory,
and run it with `ansible-builder introspect .` it works.

Is it really necessary to force users to use this path? it could be a bit inconvenient when downloading collections using `git` or their tarballs

- Ideally, you should be able to pass just a git repo folder and it should work
- If it's necessary to use the Ansible collection path, I think the help page could elaborate a bit more on what is the Ansible collection path, i.e. contain a reference to a corresponding doc page (I'll think about this). If i got confused, users also can get confused.

**Comment by Andersson007** [comment]
ready for review https://github.com/ansible/ansible-builder/pull/551
