### ISSUE TITLE
How to specify collection versions in requirements.yml?

### ISSUE THREAD

**Issue by Andersson007** [ansible/ansible-builder#548]
I don't see in https://ansible-builder.readthedocs.io/en/stable/definition/ a way to specify collection versions in `requirements.yml`.

I tried the following:
```
community.postgresql==2.0.0
community.postgresql:==2.0.0
```
and the same ^ but in quotes. Failed

If this feature doesn't exist yet, it's very important to have it.
If it exists, please update the docs.

**Comment by tuxpreacher** [comment]
There are examples here: https://docs.ansible.com/ansible/5/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

In the `requirements.yml` file I've never used `==`, I've just specified the exact version behind the `version` key.

**Comment by Andersson007** [comment]
@tuxpreacher thanks for the link, cool, i think it'd be useful if there's an example right in the builder docs (same as for other keys like ansible-core, etc.) + a link to the guide you shared.

**Comment by Andersson007** [comment]
@tuxpreacher I'll update it.

**Comment by Andersson007** [comment]
ready for review https://github.com/ansible/ansible-builder/pull/549
