### ISSUE TITLE
Establish pattern for running integration tests by invoking script that outputs xml test result

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-builder#56]
We want to be able to execute integration tests from the testing pipeline/provider of our choice.

To make our integration tests easy to execute from whatever location, and consume the results, have both the test setup and test execution wrapped in a bash script that after the test run, leaves a junit style xml file as output.

Suggested implementation:

1) create a folder for integration tests that you can not run during normal unit tests
2) In that folder, create a `conftest.py` file with a fixture like this (may take some small changes to work here) [complete proxy cli fixture from runner](https://github.com/ansible/ansible-runner/blob/devel/test/integration/containerized/conftest.py#L21-L70)
3) create a test file and that file create a test that does something simple like:

psuedocode:
```
def test_help(cli):
   result = cli(['ansible-builder', 'help'])
   assert 'something that is in help text' in result.stdout
```

4) now that you have a test, create a shell script that 
   - does any python installs/environment setup necessary to run tests
   - calls pytest, passing to it path to the integration test folder and passes flag `--junitxml=path/to/results.xml`. Docs: https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files

Acceptance criteria:
  - [ ] user/CI only needs to call `tools/run_integration.sh` or whatever name and script takes care of any dependency installs, runs tests, and leaves behind a `artifacts/results.xml` file that is always named the same thing

In the future more tests can be added, and this will be transparent to whatever CI runner is running the tests. If there are system requirements this is assumed to be taken care of by the CI runner, so please just document these dependencies.

Optional additional features:
- [ ] accept RUNNER_FORK and RUNNER_BRANCH environment variables to chose what runner to install from git
- [ ] accept TESTEXPR environment variable to pass to pytest `-k ` test selector option

**Comment by kdelee** [comment]
@beeankha this is what we talked about

**Comment by AlanCoding** [comment]
@kdelee is this already running and producing the junit output? We need to build out test cases, but that's not the same issue as this.

**Comment by kdelee** [comment]
yes we can close
