### ISSUE TITLE
Deprecate and warn about all the things

### ISSUE THREAD

**Issue by Shrews** [ansible/ansible-builder#565]
Things we need to deprecate and issue warnings for in `3.0`:

- [ ] using v1 and v2 EE schemas
- [ ] using the default base image in a v3 schema
- [ ] using `-v N` and `--verbosity` options instead of `-vvv`

**Comment by Akasurde** [comment]
- https://github.com/ansible/ansible-builder/pull/574
- https://github.com/ansible/ansible-builder/pull/591

**Comment by AlanCoding** [comment]
> using the default base image in a v3 schema

https://github.com/ansible/ansible-builder/blob/eb7d8f12147d6bccbf6d7ec1c58486bc5608752b/src/ansible_builder/constants.py#L20

Yes, this is painful because any given newcomer tries builder and then gets images derived from this outdated image which has many many problems. Found in https://groups.google.com/g/awx-project/c/cT_m0JkwmXg

**Comment by muellerju-thn** [comment]
Hi.
We are also having issues when creating an Ansible execution environment.  
When we try to use [the ee-29-rhel8 image](https://catalog.redhat.com/software/containers/ansible-automation-platform-24/ee-29-rhel8/63a3322ccdc6fa07ca9d7527?tag=1.0.0-323&push_date=1691434576000) or [this 'supported EE' image](https://catalog.redhat.com/software/containers/ansible-automation-platform-24/ee-supported-rhel9/643d4c7255839fe0f27b0f30?tag=1.0.0-378&push_date=1691434576000) as a base image, multiple errors occur when building the EE with ansible-builder (fixing/working around one after the other has taken hours, the current error is particularly strange).  
Are these execution environments intended to be used as base images? If not, where can we get working base images? The official documentation doesn't seem to be very helpful in this regard.

Update: I managed to create a new EE from the newest version of ee-supported-rhel8 (registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:1.0.0-389) with updated collection requirements.

**Comment by Akasurde** [comment]
All action items are complete. Marking this as complete.
