### ISSUE TITLE
Installing an RPM to EE Minimal

### ISSUE THREAD

**Issue by TheITRx** [ansible/ansible-builder#600]
EE minimal doesn't have dnf/yum for me to install a new repo and system package. 

Currently the suggested way is via bindep to install system packages. 

What I'm trying to accomplish really is installing Azure CLI. It involves installing an RPM from Microsoft and then installing the package via dnf. 

I'm able to accomplish things via ee-supported base image. But I dont want to use that. 

What are my options? 

ee minimal -> ansible-automation-platform-24/ee-minimal-rhel8
ee support --> ansible-automation-platform-24/ee-supported-rhel8

**Comment by sivel** [comment]
This has been documented, but not pushed to stable yet:

https://ansible.readthedocs.io/projects/builder/en/latest/scenario_guides/scenario_custom/
https://ansible.readthedocs.io/projects/builder/en/latest/definition/#version-3-sample-file

Effectively, you need to specify to use `/usr/bin/microdnf`:

```
options:
  package_manager_path: /usr/bin/microdnf
```

**Comment by TheITRx** [comment]
I appreciate the response!

dnf works on the supported base image but not on the minimal. 

However, microdnf works on minimal.

I'm all set! Thank you!

**Comment by Akasurde** [comment]
Closing as per the above comment. Thanks.
