### ISSUE TITLE
Skipping Galaxy server https://galaxy.ansible.com/api/

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/ansible-builder#609]
Hello,
since last weekend, suddenly (nothing was changed on our side), we started to get that error, when running "Project Update" in Ansible AWX 23.2.0:

```
"[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an",
    "unexpected error when getting available versions of collection",
    "community.general: '/api/v3/plugin/ansible/content/published/collections/index/",
    "community/general/versions/'",
    "ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'"
```

Sample of the `requirements.yml` (different version of the collection were tested and all got the same error):

```
collections:
  - name: community.general
    version: 7.0.1
  - name: community.windows
    version: 2.0.0
```

We tried to run the same on a local container build only to troubleshoot the problem and got the same error. We did deploy another different version of AWX and got the same error.

We did check, and the URL `'/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'` is correct.
There is no any issue, if we run `ansible-galaxy collection install community.general`. That worked.  

Important: the issue is not for **all** collections. For example, when the `community.general` is commented on, the `community.windows` is installed with no issues. If the `community.general` is not commented on, we get that error and the process fails.

Maybe someone knows what is wrong and can help.

**Comment by sivel** [comment]
The version of ansible-core you are using is unsupported at this time.  This issue has been resolved in the following versions of ansible-core:

v2.12.8
v2.13.3
v2.14.0 (and all newer versions)

* https://github.com/ansible/ansible/issues/77911
* https://github.com/ansible/ansible/pull/78325

**Comment by unbreakabl3** [comment]
Hi, @sivel .
Thank you so much for the quick reply. So, the solution is to downgrade the AWX Operator, which will downgrade the AWX?
Because my problem is that we didnt change anything...

**Comment by sivel** [comment]
I have no insight into AWX or the Operator.  Since this does not appear to be builder related, you probably need to reach out to https://github.com/ansible/awx/ or other appropriate repository.

**Comment by unbreakabl3** [comment]
Got it. Thanks a lot!
