### ISSUE TITLE
[Feature request]: Support image labels

### ISSUE THREAD

**Issue by vvarga007** [ansible/ansible-builder#625]
I want to add custom LABELs to the image during the image build.
As I see, this is not supported by ansible-builder.

**Comment by Shrews** [comment]
Use `additional_build_steps` (https://ansible.readthedocs.io/projects/builder/en/stable/definition/#additional-build-steps) to add any custom instruction file contents you wish to the final image. Example:

```
additional_build_steps:
    append_final:
        - LABEL my_fancy_label=xyz
```

**Comment by vvarga007** [comment]
Oh, that works! 
Thank you very much!
