### ISSUE TITLE
Update link to EE getting started guide

### ISSUE THREAD

**Issue by samccann** [ansible/ansible-builder#632]
The execution environment getting started guide as move to https://ansible.readthedocs.io/en/latest/getting_started_ee/index.html

Update the url introduced in https://github.com/ansible/ansible-builder/pull/580 to point to the new location.

**Comment by samccann** [comment]
if someone with the power can label this as good first issue or easyfix... that would be cool ;-)

**Comment by Vokuc** [comment]
First timer here! Need more clarity on the issue

**Comment by Akasurde** [comment]
@Vokuc Thanks for volunteering. 

The line https://github.com/ansible/ansible-builder/blob/11acf59c5f34f96db8fe7fb824163af4b7f1c69d/docs/index.rst?plain=1#L34 here needs to updated with https://ansible.readthedocs.io/en/latest/getting_started_ee/index.html

Notice the change from `devel` to `latest`.

Let me know if you need any additional help. Thanks.
