### ISSUE TITLE
Support recent versions of setuptools

### ISSUE THREAD

**Issue by PierreR** [ansible/ansible-builder#639]
The current requirement forces a version of setuptools below 67.7.3 while the latest version is currently 69.x.y

This makes it very hard to build `ansible-builder` with [nixpkgs from the 23.11 branch](https://search.nixos.org/packages?channel=23.11&show=python311Packages.setuptools&from=0&size=50&sort=relevance&type=packages&query=python311Packages.setup) which uses as a default setuptools 68.2.2

It would be awesome if newer versions of setuptools (at least up to 68.2.2) could be supported.

**Comment by Melkor333** [comment]
FYI I created a currently in-progress [pull request for nixpkgs](https://github.com/NixOS/nixpkgs/pull/290631) where I just manually removed the upper limit as it worked without any issues.
Is there a reason for this upper bounds or could this just be removed?
