### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'

### ISSUE THREAD

**Issue by DorBreger** [ansible/ansible-builder#657]
when running ansible-build and requiring community.general. Here are my files
[requierments.txt](https://github.com/ansible/ansible-builder/files/14603846/requierments.txt)
execution-enviroment.yml:
```---
version: 1
dependencies:
  galaxy: requirments.yml
  python: requierments.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools```

requirments.yml:
```---
collections:
  - lowlydba.sqlserver
  - community.general```
 I am running with `ansible-builder build --tag sqlrunner --container-runtime docker`

**Comment by DorBreger** [comment]
[output.txt](https://github.com/ansible/ansible-builder/files/14603942/output.txt)
this is the full output of the command

**Comment by Akasurde** [comment]
Please update Ansible and Ansible Builder versions. This issue is already resolved.

**Comment by DorBreger** [comment]
I am running on the latest version of ansible-builder. `ansible-builder --version` gives 3.0.1.

**Comment by DorBreger** [comment]
As for ansible, I don't even have it installed. It's not required

**Comment by Akasurde** [comment]
@DorBreger Could you please update the `execution-enviroment.yml` to version 3 as per - https://ansible.readthedocs.io/projects/builder/en/latest/definition/#version-3-sample-file?

**Comment by sivel** [comment]
The underlying problem is that the v1 schema uses a no longer supported base image, that includes an unsupported ansible-core version.

As indicated in https://github.com/ansible/ansible-builder/issues/657#issuecomment-1997888642 you will need to update to the v3 schema, and explicitly install a supported ansible-core version.

**Comment by DorBreger** [comment]
Thank you. This worked. you might want to rewrite the [introduction](https://www.ansible.com/blog/introduction-to-ansible-builder)

**Comment by Akasurde** [comment]
@DorBreger Thanks for the update. The introduction blog post is old (2020), you might want to visit https://www.redhat.com/en/blog/unlocking-efficiency-harnessing-the-capabilities-of-ansible-builder-3.0 for the latest updates.

**Comment by DorBreger** [comment]
Thank you @Akasurde. At least now this problem will be indexed by search engines :)
