### ISSUE TITLE
Ansible Galaxy check script error message may be somewhat misleading

### ISSUE THREAD

**Issue by brookelew** [ansible/ansible-builder#694]
In scripts/check_galaxy, it gives a ```  The 'ansible-galaxy' command is not found in the base image. ``` message if the return code of ```ansible-galaxy --version``` is not 0, which could be caused by other things, e.g. incorrect ansible.cfg even if ansible-galaxy is installed.

**Comment by Shrews** [comment]
Thank you for the report. I can see where this message may be misleading in that circumstance. Something along the lines of `There was a problem with the 'ansible-galaxy' command` or similar may be better.
