### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by RP-TSB** [ansible/ansible-builder#703]
Hello Team, while on v3.1.0, using the options>tags key causes it to fail.
vscode also alerts of the key not being defined in schema while linting.

The solution to this would be updating the documentation as per the currently valid options.

**Comment by Shrews** [comment]
Can you provide an example where `tags` does not work for you? Seems to work from my simple tests.

As for the vscode issue, I suspect that `ansible-lint` needs to be updated for the latest `3.1` schema changes. You will need to open a bug report for that product.

**Comment by RP-TSB** [comment]
Hello @Shrews , sorry, I feel really dumb, I updated ansible-lint in the correct virtual env and it stopped failing.
