### ISSUE TITLE
Support some means of customizing Galaxy server settings

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#79]
The galaxy CLI install commands are part of the Containerfile. Because it's a clean, replicable, environment it will use the Ansible defaults. There needs to be a means of passing a token and other settings for a private account to an Automation Hub server.

The challenge here is that we can't have any credentials left anywhere in the image, in intermediary layers, and maybe not in the build context at all. We will want building with the build context to be replicable, but that seems impossible to reconcile with providing a protected secret token.

----

My only readily available solution that doesn't involving tweaking the requirements:

 - perform `ansible-galaxy collection download` as a subprocess before starting any form of building, and store the output in build context
 - ADD the downloaded content to the image
 - Inside the container, install the downloaded content

Downside is that this would require a relatively recent Ansible version.

Some other options are probably possible, but will require discussion.

**Comment by AlanCoding** [comment]
Note: discussed solution is messy and not ideal.

We would prefer to use simple podman / docker build args, but need to assure they do not get recorded in image.

**Comment by AlanCoding** [comment]
I am hesitating at that suggestion to use build args.

https://pythonspeed.com/articles/docker-build-secrets/

It looks like they are present in the history of the final image. There is no important circumstance where this would be acceptable for the Ansible settings here.

**Comment by shanemcd** [comment]
It seems like build args might be ok if we use multi-stage builds. They do not show up in the output of `history` when run against the final image.

**Comment by beeankha** [comment]
PR https://github.com/ansible/ansible-builder/pull/137 has been merged, closing this issue!
