### ISSUE TITLE
Create Official Builder Documentation

### ISSUE THREAD

**Issue by beeankha** [ansible/ansible-builder#82]
Ansible Builder needs some documentation that is going to be similar in structure/style to [Ansible Runner's documentation](https://ansible-runner.readthedocs.io/en/latest/).  

The documentation should contain very specific information in it about how to configure and build a specific EE image, step-by-step.

Deadline: end of September, 2020.

**Comment by shanemcd** [comment]
This exists now: https://ansible-builder.readthedocs.io
