### ISSUE TITLE
Better error message when you do not have podman

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#86]
podman is the default, but I have Docker on my machine. I run a command using the default and get this:

```
$ ansible-builder build \
>   -f test/data/pytz/execution-environment.yml \
>   -c my_new_bc \
>   -t my_new_tag
Writing partial Containerfile without collection requirements
Running command:
  podman build -f my_new_bc/Containerfile -t my_new_tag my_new_bc
FileNotFoundError: [Errno 2] No such file or directory: 'podman': 'podman'
```

This is going to be a common thing to hit, and the program can give much better guidance than this.

**Comment by beeankha** [comment]
Closing, PR https://github.com/ansible/ansible-builder/pull/124 has been merged.
